use crate::DWORD;

/// A `CTRL+C` signal was received, either from keyboard input or from a signal generated by the
/// [`GenerateConsoleCtrlEvent`] function.
pub const CTRL_C_EVENT: DWORD = 0;

/// A `CTRL+BREAK` signal was received, either from keyboard input or from a signal generated by
/// [`GenerateConsoleCtrlEvent`].
pub const CTRL_BREAK_EVENT: DWORD = 1;

/// A signal that the system sends to all processes attached to a console when the user closes the
/// console (either by clicking Close on the console window's window menu, or by clicking the End
/// Task button command from Task Manager).
pub const CTRL_CLOSE_EVENT: DWORD = 2;

/// A signal that the system sends to all console processes when a user is logging off. This signal
/// does not indicate which user is logging off, so no assumptions can be made.
///
/// Note that this signal is received only by services. Interactive applications are terminated at
/// logoff, so they are not present when the system sends this signal.
pub const CTRL_LOGOFF_EVENT: DWORD = 5;

/// A signal that the system sends when the system is shutting down. Interactive applications are
/// not present by the time the system sends this signal, therefore it can be received only be
/// services in this situation. Services also have their own notification mechanism for shutdown
/// events.
pub const CTRL_SHUTDOWN_EVENT: DWORD = 6;
