mod client_create_struct;
mod create_struct_a;
mod create_struct_w;
mod high_contrast_a;
mod high_contrast_w;
mod mdi_create_struct_a;
mod mdi_create_struct_w;
mod minimized_metrics;
mod msg;
mod non_client_metrics_a;
mod non_client_metrics_w;
mod os_version_info_a;
mod os_version_info_ex_a;
mod os_version_info_ex_w;
mod os_version_info_w;
mod paint_struct;
mod wnd_class_a;
mod wnd_class_ex_a;
mod wnd_class_ex_w;
mod wnd_class_w;

pub use client_create_struct::CLIENTCREATESTRUCT;
pub use create_struct_a::CREATESTRUCTA;
pub use create_struct_w::{CREATESTRUCTW, CREATESTRUCTW as CREATESTRUCT};
pub use high_contrast_a::HIGHCONTRASTA;
pub use high_contrast_w::{HIGHCONTRASTW, HIGHCONTRASTW as HIGHCONTRAST};
pub use mdi_create_struct_a::MDICREATESTRUCTA;
pub use mdi_create_struct_w::{MDICREATESTRUCTW, MDICREATESTRUCTW as MDICREATESTRUCT};
pub use minimized_metrics::MINIMIZEDMETRICS;
pub use msg::MSG;
pub use non_client_metrics_a::NONCLIENTMETRICSA;
pub use non_client_metrics_w::{NONCLIENTMETRICSW, NONCLIENTMETRICSW as NONCLIENTMETRICS};
pub use os_version_info_a::OSVERSIONINFOA;
pub use os_version_info_ex_a::OSVERSIONINFOEXA;
pub use os_version_info_ex_w::{OSVERSIONINFOEXW, OSVERSIONINFOEXW as OSVERSIONINFOEX};
pub use os_version_info_w::{OSVERSIONINFOW as OSVERSIONINFO, OSVERSIONINFOW};
pub use paint_struct::PAINTSTRUCT;
pub use wnd_class_a::WNDCLASSA;
pub use wnd_class_ex_a::WNDCLASSEXA;
pub use wnd_class_ex_w::{WNDCLASSEXW, WNDCLASSEXW as WNDCLASSEX};
pub use wnd_class_w::{WNDCLASSW, WNDCLASSW as WNDCLASS};
